# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef61c4fc689eae2b3cdbb0b74f7b3d831b0c5ddeb8ab5d30b5b1f1a0fcaa83e7c4618f9ef81266cbf204dd86f868a1dcc3a2fcebe99f874f615b04ca0d29ae0b

test:
  secret_key_base: 9f07fb61fbf786b839e22e3dd272560df55d432ec164aeb83def24c06816a0f977d337bec186e65049c8ac41961bd43715f835bdb802b3b503d5f85770e46e56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
