# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#Criar dois usuarios, um administrador e um nao para iniciais:
Usuario.create(email: 'admin@gmail.com', password: '12345678', password_confirmation: '12345678', admin: true)
Usuario.create(email: 'usuario@gmail.com', password: '12345678', password_confirmation: '12345678')

#Criar tipos de teste:
Tipo.create(tipo: 'Calca Masc.')
Tipo.create(tipo: 'Calca Fem.')
Tipo.create(tipo: 'Bermuda Masc.')
Tipo.create(tipo: 'Bermuda Fem.')
Tipo.create(tipo: 'Short Masc.')
Tipo.create(tipo: 'Short Fem.')
Tipo.create(tipo: 'Pulseira Fem')
Tipo.create(tipo: 'Saia Fem.')
Tipo.create(tipo: 'Sunga Masc.')
Tipo.create(tipo: 'Calca Masc.Capri')
Tipo.create(tipo: 'Calca Fem.Capri')
Tipo.create(tipo: 'Calca Fem.Corsario')
Tipo.create(tipo: 'Calca Fem. Cropped')
Tipo.create(tipo: 'Cachecol Unissex')
Tipo.create(tipo: 'PAC')
Tipo.create(tipo: 'Saia Calca')
Tipo.create(tipo: 'Polo Masc.')
Tipo.create(tipo: 'Polo Fem.')
Tipo.create(tipo: 'Camiseta Unissex')
Tipo.create(tipo: 'Camisa Fem.')
Tipo.create(tipo: 'Camisa Masc.')
Tipo.create(tipo: 'Jaqueta Fem.')
Tipo.create(tipo: 'Jaqueta Masc.')
Tipo.create(tipo: 'Camiseta Fem.')
Tipo.create(tipo: 'Camiseta Masc.')
Tipo.create(tipo: 'Blusa Fem.')
Tipo.create(tipo: 'Blusa Masc.')
Tipo.create(tipo: 'Regata Fem.')
Tipo.create(tipo: 'Regata Masc.')
Tipo.create(tipo: 'Blusao Fem.')
Tipo.create(tipo: 'Blusao Masc.')
Tipo.create(tipo: 'Body')
Tipo.create(tipo: 'Chapeu,Bone Unissex')
Tipo.create(tipo: 'Vestido')
Tipo.create(tipo: 'Chaveiro Unissex')
Tipo.create(tipo: 'Top')
Tipo.create(tipo: 'Chaveiro Fem.')
Tipo.create(tipo: 'Casaco Fem.')
Tipo.create(tipo: 'Casaco Masc.')
Tipo.create(tipo: 'Colete Fem.')
Tipo.create(tipo: 'Colete Masc.')
Tipo.create(tipo: 'Pulseira Fem.')
Tipo.create(tipo: 'Caban Masc.')
Tipo.create(tipo: 'Macacao Fem.')
Tipo.create(tipo: 'Macacao Masc.')
Tipo.create(tipo: 'Jardineira Fem.')
Tipo.create(tipo: 'Jardineira Masc.')
Tipo.create(tipo: 'Blazer Fem.')
Tipo.create(tipo: 'Blazer Masc.')
Tipo.create(tipo: 'Biquine')
Tipo.create(tipo: 'Sapato Unissex')
Tipo.create(tipo: 'Maio')
Tipo.create(tipo: 'Capa Unissex')
Tipo.create(tipo: 'Acessorio')
Tipo.create(tipo: 'Sapato Masc.')
Tipo.create(tipo: 'Sapato Fem.')
Tipo.create(tipo: 'Marketing')
Tipo.create(tipo: 'Twin Set')
Tipo.create(tipo: 'Luvas')
Tipo.create(tipo: 'Langerie')
Tipo.create(tipo: 'Cueca Masc.')
Tipo.create(tipo: 'Cueca Fem.')
Tipo.create(tipo: 'Cache Coeur')
Tipo.create(tipo: 'Lenco Fem.')
Tipo.create(tipo: 'Sleeve/Bolero')
Tipo.create(tipo: 'Bijouterias Unissex')
Tipo.create(tipo: 'Cachecol')
Tipo.create(tipo: 'Meia Unissex')
Tipo.create(tipo: 'Xale')
Tipo.create(tipo: 'Estola')
Tipo.create(tipo: 'Bolsa Unissex')
Tipo.create(tipo: 'PONCHO')
Tipo.create(tipo: 'Meia Masc.')
Tipo.create(tipo: 'Meia Fem.')
Tipo.create(tipo: 'Cinto Masc.')
Tipo.create(tipo: 'Cinto Fem.')
Tipo.create(tipo: 'Bolsa/Carteira Masc.')
Tipo.create(tipo: 'Bolsa/Carteira Fem.')
Tipo.create(tipo: 'Mochila Masc.')
Tipo.create(tipo: 'Mochila Fem.')
Tipo.create(tipo: 'Bone/Chapeu Masc.')
Tipo.create(tipo: 'Bone/Chapeu Fem.')
Tipo.create(tipo: 'Bijouteria Masc.')
Tipo.create(tipo: 'Bijouteria Fem.')
Tipo.create(tipo: 'Cinto Unissex')
Tipo.create(tipo: 'Carteira Unissex')
Tipo.create(tipo: 'Bone/Chapeu/Vis Unissex')
Tipo.create(tipo: 'Soutien')
Tipo.create(tipo: 'Calcinha')
Tipo.create(tipo: 'Salopete Fem.')
Tipo.create(tipo: 'Carteira Masc.')
Tipo.create(tipo: 'Carteira Fem.')
Tipo.create(tipo: 'Chaveiro Masc.')
Tipo.create(tipo: 'Bracelete Fem.')
Tipo.create(tipo: 'Bracelete Masc.')
Tipo.create(tipo: 'Calcinha Fem.')
Tipo.create(tipo: 'Avental Unissex')
Tipo.create(tipo: 'Jogo Americado')
Tipo.create(tipo: 'Peca Piloto Prototipo')
Tipo.create(tipo: 'Lenco Unissex')
Tipo.create(tipo: 'Caban Fem.')
Tipo.create(tipo: 'Poncho Masc.')
Tipo.create(tipo: 'Tiara Fem.')
Tipo.create(tipo: 'Mochila Unissex')
Tipo.create(tipo: 'Camisola Fem.')
Tipo.create(tipo: 'Porta Joias')
Tipo.create(tipo: 'Pelerine Fem.')
Tipo.create(tipo: 'Perfume Unissex')
Tipo.create(tipo: 'Perfume Fem.')
Tipo.create(tipo: 'Perfume Masc.')
Tipo.create(tipo: 'Cosmetico Unissex')
Tipo.create(tipo: 'Cosmetico Fem.')
Tipo.create(tipo: 'Agenda Unissex')
Tipo.create(tipo: 'Echarpe Fem.')
Tipo.create(tipo: 'Echarpe Masc.')
Tipo.create(tipo: 'Toalha')
Tipo.create(tipo: 'Gravata Masc.')
Tipo.create(tipo: 'Chemisier')
Tipo.create(tipo: 'Jaqueta Masc Tricot')
Tipo.create(tipo: 'Tunica Fem.')
Tipo.create(tipo: 'Terno Masc')
Tipo.create(tipo: 'Blusa Fem.Trico')
Tipo.create(tipo: 'Blusa Masc.Trico')
Tipo.create(tipo: 'Cardigan Fem.')
Tipo.create(tipo: 'Cardigan Masc.')
Tipo.create(tipo: 'Blusao Fem.Trico')
Tipo.create(tipo: 'Blusao Masc.Trico')
Tipo.create(tipo: 'Cardigan Fem.Trico')
Tipo.create(tipo: 'Cardigan Masc.Trico')
Tipo.create(tipo: 'Vestido Fem.Trico')
Tipo.create(tipo: 'Bracelete Unissex')
Tipo.create(tipo: 'Pijama Fem.')
Tipo.create(tipo: 'Cachecol Unissex Trico')
Tipo.create(tipo: 'Casaco Fem.Trico')
Tipo.create(tipo: 'Casaco Masc.Trico')
Tipo.create(tipo: 'TERNO FEM')
Tipo.create(tipo: 'Jaqueta Fem Tricot')
Tipo.create(tipo: 'Abotoadura')
Tipo.create(tipo: 'Relogio Masc')
Tipo.create(tipo: 'Chinelo Fem')
Tipo.create(tipo: 'Relogio Unissex')
Tipo.create(tipo: 'Poncho Fem Tricot')
Tipo.create(tipo: 'Sueter Trico Masc.')
Tipo.create(tipo: 'Pelerine Fem Tricot')
Tipo.create(tipo: 'BLAZER MASC TRICOT')
Tipo.create(tipo: 'Saia Fem Tricot')
Tipo.create(tipo: 'Pijama Masc.')
Tipo.create(tipo: 'Calca Fem Tricot')
Tipo.create(tipo: 'Touca Unissex')
Tipo.create(tipo: 'Regata Fem Tricot')
Tipo.create(tipo: 'Colete Fem Trico')
Tipo.create(tipo: 'Kaftan Fem.')
Tipo.create(tipo: 'MINI COAT')
Tipo.create(tipo: 'LUVAS FEM TRICOT')
Tipo.create(tipo: 'Cachecol Fem.Trico')
Tipo.create(tipo: 'Polo Fem Tricot')
Tipo.create(tipo: 'Polo Masc. Trico')
Tipo.create(tipo: 'Cachecol Masc Tricot')
Tipo.create(tipo: 'CACHECOL MASC')
Tipo.create(tipo: 'Relogio Fem')
Tipo.create(tipo: 'BOLERO FEM TRICOT')
Tipo.create(tipo: 'CABAN FEM TRICOT')
Tipo.create(tipo: 'Camiseta Masc Trico')
Tipo.create(tipo: 'FAIXA FEM')
Tipo.create(tipo: 'Gola')
Tipo.create(tipo: 'KIMONO FEM')
Tipo.create(tipo: 'Oculos Masc.')
Tipo.create(tipo: 'Oculos Fem.')
Tipo.create(tipo: 'Oculos Unissex')
Tipo.create(tipo: 'Sueter Fem Trico')
Tipo.create(tipo: 'Bermuda Fem Trico')
Tipo.create(tipo: 'Kaftan fem. trico')
Tipo.create(tipo: 'Capa fem trico')
Tipo.create(tipo: 'Capa Fem')
Tipo.create(tipo: 'Kimono Fem Trico')
Tipo.create(tipo: 'Blusa Cropped')
Tipo.create(tipo: 'Body Trico')
Tipo.create(tipo: 'Vestido Tecido Plano')
Tipo.create(tipo: 'Bijouteria fem')
Tipo.create(tipo: 'BIJOUTERIA FEM')
Tipo.create(tipo: '340')
Tipo.create(tipo: '343')
Tipo.create(tipo: 'Vestido Longo')
Tipo.create(tipo: '350')
Tipo.create(tipo: '441')
Tipo.create(tipo: '443')
Tipo.create(tipo: 'SANDALIA FEM')
Tipo.create(tipo: 'SAPATO FEMININO')
Tipo.create(tipo: 'BOTA FEMININA')
Tipo.create(tipo: 'TENIS FEMININO')
Tipo.create(tipo: 'TENIS MASCULINO')
Tipo.create(tipo: 'CHINELO MASC')
Tipo.create(tipo: 'BOTA MASCULINA')
Tipo.create(tipo: 'SAPATO MASCULINO')
Tipo.create(tipo: 'TENIS UNISSEX')
Tipo.create(tipo: 'SANDALIA MASC')
Tipo.create(tipo: 'SAPATILHA FEM')
Tipo.create(tipo: 'POLAINA')
Tipo.create(tipo: 'SANDALIA MASCULINA')
Tipo.create(tipo: 'GOLA')
Tipo.create(tipo: 'MEIA3/4')
Tipo.create(tipo: 'MEIACASUAL')
Tipo.create(tipo: 'MEIAAEROBIC')
Tipo.create(tipo: 'MEIASOQUETE')
Tipo.create(tipo: 'MEIAMICRO')
Tipo.create(tipo: 'MEIAMEDIUM')
Tipo.create(tipo: 'SAPATILHA')
Tipo.create(tipo: 'BOE')


#Criar produtos de teste:
Produto.create(cbarras: 9004011043, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 34', valor: 350, saldo: 2, tipo_id: 2)
Produto.create(cbarras: 9004011044, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 36', valor: 355, saldo: 3, tipo_id: 2)
Produto.create(cbarras: 9004011045, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 38', valor: 360, saldo: 1, tipo_id: 2)
Produto.create(cbarras: 9004011046, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 40', valor: 365, saldo: 3, tipo_id: 2)
Produto.create(cbarras: 9004011047, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 42', valor: 370, saldo: 6, tipo_id: 2)
Produto.create(cbarras: 9004011048, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 44', valor: 375, saldo: 1, tipo_id: 2)
Produto.create(cbarras: 9004011049, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 46', valor: 380, saldo: 9, tipo_id: 2)
Produto.create(cbarras: 9004011050, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 34', valor: 385, saldo: 0, tipo_id: 2)
Produto.create(cbarras: 9004011051, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 36', valor: 390, saldo: 3, tipo_id: 2)
Produto.create(cbarras: 9004011052, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 38', valor: 395, saldo: 2, tipo_id: 2)
Produto.create(cbarras: 9004011053, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 40', valor: 400, saldo: 3, tipo_id: 2)
Produto.create(cbarras: 9004011054, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 42', valor: 405, saldo: 1, tipo_id: 2)
Produto.create(cbarras: 9004011055, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 44', valor: 410, saldo: 3, tipo_id: 2)
Produto.create(cbarras: 9004011056, descricao: 'CALCA CORY INDIGO BORD INDIGO 600 46', valor: 415, saldo: 6, tipo_id: 2)
Produto.create(cbarras: 9004011057, descricao: 'CALCA ALEX 2 INDIGO INDIGO 600 36', valor: 420, saldo: 1, tipo_id: 1)
Produto.create(cbarras: 9004011058, descricao: 'CALCA ALEX 2 INDIGO INDIGO 600 38', valor: 425, saldo: 9, tipo_id: 1)
Produto.create(cbarras: 9004011059, descricao: 'CALCA ALEX 2 INDIGO INDIGO 600 40', valor: 430, saldo: 0, tipo_id: 1)
Produto.create(cbarras: 9004011060, descricao: 'CALCA ALEX 2 INDIGO INDIGO 600 42', valor: 435, saldo: 3, tipo_id: 1)
Produto.create(cbarras: 9004011061, descricao: 'CALCA ALEX 2 INDIGO INDIGO 600 44', valor: 440, saldo: 2, tipo_id: 1)
Produto.create(cbarras: 9004011062, descricao: 'CALCA ALEX 2 INDIGO INDIGO 600 46', valor: 445, saldo: 3, tipo_id: 1)
Produto.create(cbarras: 9004011063, descricao: 'CALCA ALEX 2 INDIGO INDIGO 600 48', valor: 450, saldo: 1, tipo_id: 1)
Produto.create(cbarras: 9004011064, descricao: 'CALCA ALEX 2 INDIGO INDIGO 600 50', valor: 455, saldo: 3, tipo_id: 1)
Produto.create(cbarras: 9004011065, descricao: 'CALCA ALEX 2 INDIGO INDIGO 600 52', valor: 460, saldo: 6, tipo_id: 1)
Produto.create(cbarras: 9004011066, descricao: 'CALCA ALEX 2 INDIGO INDIGO 600 54', valor: 465, saldo: 1, tipo_id: 1)
Produto.create(cbarras: 9004011067, descricao: 'CALCA ALEX 2 INDIGO INDIGO 600 56', valor: 470, saldo: 9, tipo_id: 1)
Produto.create(cbarras: 9004011068, descricao: 'CALCA TOM INDIGO INDIGO 600 36', valor: 475, saldo: 0, tipo_id: 1)
Produto.create(cbarras: 9004011069, descricao: 'CALCA TOM INDIGO INDIGO 600 37', valor: 480, saldo: 3, tipo_id: 1)
Produto.create(cbarras: 9004011070, descricao: 'CALCA TOM INDIGO INDIGO 600 38', valor: 485, saldo: 2, tipo_id: 1)
Produto.create(cbarras: 9004011071, descricao: 'CALCA TOM INDIGO INDIGO 600 39', valor: 490, saldo: 3, tipo_id: 1)
Produto.create(cbarras: 9004011072, descricao: 'CALCA TOM INDIGO INDIGO 600 40', valor: 495, saldo: 1, tipo_id: 1)
Produto.create(cbarras: 9004011073, descricao: 'CALCA TOM INDIGO INDIGO 600 41', valor: 500, saldo: 3, tipo_id: 1)
Produto.create(cbarras: 9004011074, descricao: 'CALCA TOM INDIGO INDIGO 600 42', valor: 505, saldo: 6, tipo_id: 1)
Produto.create(cbarras: 9004011075, descricao: 'CALCA TOM INDIGO INDIGO 600 43', valor: 510, saldo: 1, tipo_id: 1)
Produto.create(cbarras: 9004011076, descricao: 'CALCA TOM INDIGO INDIGO 600 44', valor: 515, saldo: 9, tipo_id: 1)
Produto.create(cbarras: 9004011077, descricao: 'CALCA TOM INDIGO INDIGO 600 45', valor: 520, saldo: 0, tipo_id: 1)
Produto.create(cbarras: 9004011078, descricao: 'CALCA TOM INDIGO INDIGO 600 46', valor: 525, saldo: 3, tipo_id: 1)
Produto.create(cbarras: 9004011079, descricao: 'BLUSA FEM ML PP', valor: 530, saldo: 2, tipo_id: 26)
Produto.create(cbarras: 9004011080, descricao: 'BLUSA FEM ML P', valor: 535, saldo: 3, tipo_id: 26)
Produto.create(cbarras: 9004011081, descricao: 'BLUSA FEM ML M', valor: 540, saldo: 1, tipo_id: 26)
Produto.create(cbarras: 9004011082, descricao: 'BLUSA FEM ML G', valor: 545, saldo: 3, tipo_id: 26)
Produto.create(cbarras: 9004011083, descricao: 'BLUSA FEM ML GG', valor: 550, saldo: 6, tipo_id: 26)
Produto.create(cbarras: 9004011084, descricao: 'BLUSA FEM ML PP', valor: 555, saldo: 1, tipo_id: 26)
Produto.create(cbarras: 9004011085, descricao: 'BLUSA FEM ML P', valor: 560, saldo: 9, tipo_id: 26)
Produto.create(cbarras: 9004011086, descricao: 'BLUSA FEM ML M', valor: 565, saldo: 0, tipo_id: 26)
Produto.create(cbarras: 9004011087, descricao: 'BLUSA FEM ML G', valor: 570, saldo: 3, tipo_id: 26)
Produto.create(cbarras: 9004011088, descricao: 'BLUSA FEM ML GG', valor: 575, saldo: 2, tipo_id: 26)
Produto.create(cbarras: 9004011089, descricao: 'BLUSA FEM ML PP', valor: 580, saldo: 3, tipo_id: 26)
Produto.create(cbarras: 9004011090, descricao: 'BLUSA FEM ML P', valor: 585, saldo: 1, tipo_id: 26)
Produto.create(cbarras: 9004011091, descricao: 'BLUSA FEM ML M', valor: 590, saldo: 3, tipo_id: 26)
Produto.create(cbarras: 9004011092, descricao: 'BLUSA FEM ML G', valor: 595, saldo: 6, tipo_id: 26)
Produto.create(cbarras: 9004011093, descricao: 'BLUSA FEM ML GG', valor: 600, saldo: 1, tipo_id: 26)
Produto.create(cbarras: 9004011094, descricao: 'BLUSA FEM ML PP', valor: 605, saldo: 9, tipo_id: 26)
Produto.create(cbarras: 9004011095, descricao: 'BLUSA FEM ML P', valor: 610, saldo: 0, tipo_id: 26)
Produto.create(cbarras: 9004011096, descricao: 'BLUSA FEM ML M', valor: 615, saldo: 3, tipo_id: 26)
Produto.create(cbarras: 9004011097, descricao: 'BLUSA FEM ML G', valor: 620, saldo: 2, tipo_id: 26)
Produto.create(cbarras: 9004011098, descricao: 'BLUSA FEM ML GG', valor: 625, saldo: 3, tipo_id: 26)
Produto.create(cbarras: 9004011099, descricao: 'VESTIDO FEM ML PP', valor: 630, saldo: 1, tipo_id: 34)
Produto.create(cbarras: 9004011100, descricao: 'VESTIDO FEM ML P', valor: 635, saldo: 3, tipo_id: 34)
Produto.create(cbarras: 9004011101, descricao: 'VESTIDO FEM ML M', valor: 640, saldo: 6, tipo_id: 34)
Produto.create(cbarras: 9004011102, descricao: 'VESTIDO FEM ML G', valor: 645, saldo: 1, tipo_id: 34)
Produto.create(cbarras: 9004011103, descricao: 'VESTIDO FEM ML GG', valor: 650, saldo: 9, tipo_id: 34)
Produto.create(cbarras: 9004011104, descricao: 'VESTIDO FEM ML PP', valor: 655, saldo: 0, tipo_id: 34)
Produto.create(cbarras: 9004011105, descricao: 'VESTIDO FEM ML P', valor: 660, saldo: 3, tipo_id: 34)
Produto.create(cbarras: 9004011106, descricao: 'VESTIDO FEM ML M', valor: 665, saldo: 2, tipo_id: 34)
Produto.create(cbarras: 9004011107, descricao: 'VESTIDO FEM ML G', valor: 670, saldo: 3, tipo_id: 34)
Produto.create(cbarras: 9004011108, descricao: 'VESTIDO FEM ML GG', valor: 675, saldo: 1, tipo_id: 34)
